version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cefniobveufeddadsen7
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t /var/www/html/public

  nginx:
    image: nginx:latest
    container_name: stock-nginx-1
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    command: /bin/bash -c "sleep 10 && nginx -g 'daemon off;'"

volumes:
  mysql_data:
